# Generated by Django 5.0.4 on 2025-03-26 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myNewApp1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='mailID',
            field=models.EmailField(default='_____blank', max_length=1111),
            preserve_default=False,
        ),
    ]
